# Generated by Django 3.0.8 on 2020-07-26 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShownFields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='shown_fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.ShownFields'),
        ),
    ]
