# Generated by Django 3.0.8 on 2020-07-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_auto_20200726_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linked_lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_models.Lobby'),
        ),
    ]
