# Generated by Django 3.0.8 on 2020-07-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_auto_20200726_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='linked_lobby',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='images/users', verbose_name='Изображение')),
                ('linked_lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.Lobby')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.UserInfo'),
        ),
    ]
