# Generated by Django 3.0.8 on 2020-08-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0006_userinfo_ready_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ready_status',
            new_name='ready_state',
        ),
    ]
