# Generated by Django 3.0.8 on 2020-08-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0007_auto_20200802_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_state',
            field=models.CharField(choices=[('R', 'recruiting_players'), ('S', 'game_start'), ('E', 'game_end')], default='R', max_length=1),
        ),
    ]
