# Generated by Django 3.0.8 on 2020-08-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0009_auto_20200805_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='shown_fields',
        ),
        migrations.AddField(
            model_name='shownfields',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.Person'),
        ),
    ]
