# Generated by Django 3.0.8 on 2020-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0010_auto_20200810_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('legend', models.CharField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='legend',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
