# Generated by Django 3.0.8 on 2020-08-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0011_auto_20200811_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('story', models.CharField(max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='legend',
            name='legend',
        ),
        migrations.AddField(
            model_name='legend',
            name='armor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='legend',
            name='await_time',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='legend',
            name='medicines',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='legend',
            name='square',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='story',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='legend',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.Legend'),
        ),
    ]
