# Generated by Django 3.0.8 on 2020-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0012_auto_20200811_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='number_of_seats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
