# Generated by Django 3.0.8 on 2020-08-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0014_userinfo_is_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_shown',
        ),
    ]
