# Generated by Django 3.0.8 on 2020-08-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0015_remove_userinfo_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='current_person',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PersonsQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('linked_lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.Lobby')),
            ],
        ),
    ]
