# Generated by Django 3.0.8 on 2020-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0016_auto_20200812_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='direction',
            field=models.BooleanField(default=False),
        ),
    ]
