# Generated by Django 3.0.8 on 2020-08-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0017_lobby_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='is_round_over',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PersonsKickList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('kick_person', models.CharField(max_length=20)),
                ('linked_lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_models.Lobby')),
            ],
        ),
    ]
