# Generated by Django 3.0.8 on 2020-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0018_auto_20200821_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='additional_info',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
