# Generated by Django 3.0.8 on 2020-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0019_legend_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='protection',
            field=models.BooleanField(default=False),
        ),
    ]
