# Generated by Django 3.0.8 on 2020-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0020_person_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='voices',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personskicklist',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
