# Generated by Django 3.0.8 on 2020-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0021_auto_20200830_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='speak_time',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
