# Generated by Django 3.0.8 on 2020-09-01 16:57

import db_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0022_person_speak_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=db_models.models.upload_to, verbose_name='Avatar'),
        ),
    ]
