# Generated by Django 3.0.8 on 2020-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0024_auto_20200902_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='growth',
            field=models.PositiveSmallIntegerField(default=160),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.PositiveSmallIntegerField(default=65),
        ),
    ]
